import {
  BarChart3,
  Calculator,
  FileText,
  LinkIcon,
  PackageSearch,
  PlaySquare,
  Search,
  ShoppingBag,
  Sparkles,
  Video,
} from "lucide-react";

export const toolCards = [
  {
    name: "AI Side Hustle Finder",
    slug: "ai-side-hustle-finder",
    keyword: "AI side hustle finder",
    description: "Compare realistic AI-assisted business ideas by demand, difficulty, cost, and monetization path.",
    category: "Business Ideas",
    href: "/tools/ai-side-hustle-finder",
    icon: Sparkles,
    relatedGuide: "/business-ideas/side-hustle-ideas-for-beginners",
  },
  {
    name: "Digital Product Profit Calculator",
    slug: "digital-product-profit-calculator",
    keyword: "digital product profit calculator",
    description: "Estimate template, ebook, course, or download profit after fees, tools, ads, and refunds.",
    category: "Calculators",
    href: "/calculators/digital-product-profit-calculator",
    icon: Calculator,
    relatedGuide: "/digital-products/digital-product-ideas-for-beginners",
  },
  {
    name: "Dropshipping Profit Calculator",
    slug: "dropshipping-profit-calculator",
    keyword: "dropshipping profit calculator",
    description: "Check product margin after supplier cost, shipping, payment fees, ads, and return allowance.",
    category: "Calculators",
    href: "/calculators/dropshipping-profit-calculator",
    icon: BarChart3,
    relatedGuide: "/business-ideas/dropshipping-ideas-for-beginners",
  },
  {
    name: "Amazon Affiliate Niche Finder",
    slug: "amazon-affiliate-niche-finder",
    keyword: "Amazon affiliate niche finder",
    description: "Find beginner-friendly affiliate niches with clear buyer intent, content angles, and product depth.",
    category: "Affiliate Niches",
    href: "/affiliate-niches/amazon-affiliate-niche-finder",
    icon: LinkIcon,
    relatedGuide: "/affiliate-niches/best-affiliate-niches-for-beginners",
  },
  {
    name: "Shopify Product Margin Calculator",
    slug: "shopify-product-margin-calculator",
    keyword: "Shopify product margin calculator",
    description: "Estimate Shopify product margins after cost of goods, app fees, payment fees, and ad spend.",
    category: "Calculators",
    href: "/calculators/shopify-product-margin-calculator",
    icon: ShoppingBag,
    relatedGuide: "/business-ideas/shopify-product-research-guide",
  },
  {
    name: "Etsy Product Idea Generator",
    slug: "etsy-product-idea-generator",
    keyword: "Etsy product idea generator",
    description: "Brainstorm Etsy product ideas using demand signals, production effort, pricing, and competition.",
    category: "Digital Products",
    href: "/digital-products/etsy-product-idea-generator",
    icon: PackageSearch,
    relatedGuide: "/digital-products/etsy-digital-product-ideas",
  },
  {
    name: "YouTube Niche Finder",
    slug: "youtube-niche-finder",
    keyword: "YouTube niche finder",
    description: "Score YouTube niche ideas by audience demand, content difficulty, monetization, and repeatability.",
    category: "Business Ideas",
    href: "/tools/youtube-niche-finder",
    icon: PlaySquare,
    relatedGuide: "/business-ideas/youtube-niche-ideas-for-beginners",
  },
  {
    name: "TikTok Niche Finder",
    slug: "tiktok-niche-finder",
    keyword: "TikTok niche finder",
    description: "Find short-form content niches that connect to products, affiliate offers, or digital downloads.",
    category: "Business Ideas",
    href: "/tools/tiktok-niche-finder",
    icon: Video,
    relatedGuide: "/business-ideas/tiktok-niche-ideas-for-beginners",
  },
  {
    name: "Pinterest Product Idea Finder",
    slug: "pinterest-product-idea-finder",
    keyword: "Pinterest product idea finder",
    description: "Use Pinterest-style intent to discover product, template, printable, and affiliate content ideas.",
    category: "Digital Products",
    href: "/digital-products/pinterest-product-idea-finder",
    icon: Search,
    relatedGuide: "/digital-products/pinterest-product-research-guide",
  },
  {
    name: "Affiliate Program Finder",
    slug: "affiliate-program-finder",
    keyword: "affiliate program finder",
    description: "Match beginner-friendly niches with affiliate program types, content angles, and buying intent.",
    category: "Affiliate Niches",
    href: "/affiliate-niches/affiliate-program-finder",
    icon: FileText,
    relatedGuide: "/affiliate-niches/how-to-find-affiliate-programs",
  },
];

export const businessGuides = [
  {
    title: "Side Hustle Ideas for Beginners",
    slug: "side-hustle-ideas-for-beginners",
    href: "/business-ideas/side-hustle-ideas-for-beginners",
    description: "A practical guide to comparing simple online business ideas before spending money.",
    relatedTools: ["/tools/ai-side-hustle-finder", "/tools/youtube-niche-finder", "/tools/tiktok-niche-finder"],
  },
  {
    title: "Digital Product Ideas for Beginners",
    slug: "digital-product-ideas-for-beginners",
    href: "/digital-products/digital-product-ideas-for-beginners",
    description: "Research templates, printables, ebooks, and downloads with realistic profit expectations.",
    relatedTools: ["/calculators/digital-product-profit-calculator", "/digital-products/etsy-product-idea-generator"],
  },
  {
    title: "Best Affiliate Niches for Beginners",
    slug: "best-affiliate-niches-for-beginners",
    href: "/affiliate-niches/best-affiliate-niches-for-beginners",
    description: "Choose affiliate niches with enough demand, content depth, and beginner-friendly programs.",
    relatedTools: ["/affiliate-niches/amazon-affiliate-niche-finder", "/affiliate-niches/affiliate-program-finder"],
  },
  {
    title: "Dropshipping Ideas for Beginners",
    slug: "dropshipping-ideas-for-beginners",
    href: "/business-ideas/dropshipping-ideas-for-beginners",
    description: "Use margin, shipping, and competition checks to avoid weak dropshipping products.",
    relatedTools: ["/calculators/dropshipping-profit-calculator", "/calculators/shopify-product-margin-calculator"],
  },
  {
    title: "Pinterest Product Research Guide",
    slug: "pinterest-product-research-guide",
    href: "/digital-products/pinterest-product-research-guide",
    description: "Turn visual search intent into product, printable, template, and affiliate content ideas.",
    relatedTools: ["/digital-products/pinterest-product-idea-finder", "/calculators/digital-product-profit-calculator"],
  },
  {
    title: "YouTube Niche Ideas for Beginners",
    slug: "youtube-niche-ideas-for-beginners",
    href: "/business-ideas/youtube-niche-ideas-for-beginners",
    description: "Compare YouTube niches by content workload, search demand, and monetization options.",
    relatedTools: ["/tools/youtube-niche-finder", "/affiliate-niches/affiliate-program-finder"],
  },
  {
    title: "TikTok Niche Ideas for Beginners",
    slug: "tiktok-niche-ideas-for-beginners",
    href: "/business-ideas/tiktok-niche-ideas-for-beginners",
    description: "Find TikTok niche ideas that can connect short-form content to products, offers, or affiliate revenue.",
    relatedTools: ["/tools/tiktok-niche-finder", "/affiliate-niches/affiliate-program-finder"],
  },
  {
    title: "Shopify Product Research Guide",
    slug: "shopify-product-research-guide",
    href: "/business-ideas/shopify-product-research-guide",
    description: "Use margin, demand, fees, and fulfillment checks before choosing a Shopify product idea.",
    relatedTools: ["/calculators/shopify-product-margin-calculator", "/calculators/dropshipping-profit-calculator"],
  },
  {
    title: "Etsy Digital Product Ideas",
    slug: "etsy-digital-product-ideas",
    href: "/digital-products/etsy-digital-product-ideas",
    description: "Compare Etsy product ideas by buyer intent, production effort, price point, and competition.",
    relatedTools: ["/digital-products/etsy-product-idea-generator", "/calculators/digital-product-profit-calculator"],
  },
  {
    title: "How to Find Affiliate Programs",
    slug: "how-to-find-affiliate-programs",
    href: "/affiliate-niches/how-to-find-affiliate-programs",
    description: "A beginner checklist for finding affiliate programs that fit your niche, content, and audience.",
    relatedTools: ["/affiliate-niches/affiliate-program-finder", "/affiliate-niches/amazon-affiliate-niche-finder"],
  },
];

export function getToolBySlug(slug: string) {
  return toolCards.find((tool) => tool.slug === slug);
}

export function getGuideBySlug(slug: string) {
  return businessGuides.find((guide) => guide.slug === slug);
}
