export const popularNiches = [
    { slug: "saas", name: "SaaS", description: "Software as a Service" },
    { slug: "pet-tech", name: "Pet Tech", description: "Apps and gadgets for pet owners" },
    { slug: "coffee-subscription", name: "Coffee Subscription", description: "Direct-to-consumer coffee beans" },
    { slug: "ai-agent", name: "AI Agent", description: "Autonomous AI assistants" },
    { slug: "marketplace", name: "Marketplace", description: "Peer-to-peer trading platforms" },
    { slug: "fintech", name: "Fintech", description: "Financial technology solutions" },
    { slug: "edtech", name: "Edtech", description: "Education and learning tools" },
    { slug: "healthtech", name: "Healthtech", description: "Medical and wellness apps" },
    { slug: "ecommerce", name: "E-commerce", description: "Online retail and dropshipping" },
    { slug: "no-code", name: "No-Code", description: "Tools for building without code" },
    { slug: "agency", name: "Agency", description: "Service-based business models" },
    { slug: "micro-saas", name: "Micro-SaaS", description: "Small, niche automation tools" },
    // ... adding 100 more categories
    { slug: "clean-tech", name: "Clean Tech", description: "Sustainability and green energy" },
    { slug: "proptech", name: "Proptech", description: "Real estate and property tools" },
    { slug: "foodtech", name: "Foodtech", description: "Delivery and kitchen automation" },
    { slug: "legall-tech", name: "Legal Tech", description: "Doc automation and legal aids" },
    { slug: "beauty-box", name: "Beauty Box", description: "Subscription cosmetics" },
    { slug: "garden-tech", name: "Garden Tech", description: "Smart irrigation and plant care" },
    { slug: "web3", name: "Web3", description: "Blockchain and crypto dApps" },
    { slug: "creator-economy", name: "Creator Economy", description: "Tools for YouTubers and influencers" },
    { slug: "productivity", name: "Productivity", description: "Task managers and focus tools" },
    { slug: "mental-health", name: "Mental Health", description: "Meditation and therapy apps" },
    { slug: "parenting", name: "Parenting", description: "Smart baby monitors and advice apps" },
    { slug: "biotech", name: "Biotech", description: "Longevity and genetic research" },
    { slug: "robotics", name: "Robotics", description: "Automation for homes and warehouses" },
    { slug: "gaming", name: "Gaming", description: "Indie games and player tools" },
    { slug: "insurtech", name: "Insurtech", description: "Modern insurance platforms" },
    { slug: "travel-planner", name: "Travel Planner", description: "AI-driven itinerary tools" },
    { slug: "second-hand", name: "Second Hand", description: "Resale and thrifting marketplaces" },
    { slug: "smart-home", name: "Smart Home", description: "IoT and connected appliances" },
    { slug: "vr-ar", name: "VR/AR", description: "Immersive experiences and training" },
    { slug: "remote-work", name: "Remote Work", description: "Communication and team culture tools" },
    { slug: "subscription-vape", name: "Subscription Vape", description: "Monthly delivery services" },
    { slug: "custom-jewelry", name: "Custom Jewelry", description: "Personalized accessories" },
    { slug: "fitness-tracker", name: "Fitness Tracker", description: "Wearables and training data" },
    { slug: "yoga-studio", name: "Yoga Studio", description: "Booking and community platforms" },
    { slug: "charity-platform", name: "Charity Platform", description: "Donation and transparency tools" },
    { slug: "podcasting", name: "Podcasting", description: "Hosting and editing software" },
    { slug: "delivery-bot", name: "Delivery Bot", description: "Last-mile courier automation" },
    { slug: "dating-app", name: "Dating App", description: "Niche match-making for subcultures" },
    { slug: "solar-energy", name: "Solar Energy", description: "Panel installation and monitoring" },
    { slug: "freelance-tools", name: "Freelance Tools", description: "Invoicing and client management" },
    { slug: "api-service", name: "API Service", description: "B2B data and tool integrations" },
    { slug: "event-tech", name: "Event Tech", description: "Ticketing and hybrid event software" },
    { slug: "recruitment", name: "Recruitment", description: "AI-driven hiring platforms" },
    { slug: "music-tech", name: "Music Tech", description: "Instruments and production tools" },
    { slug: "language-learning", name: "Language Learning", description: "Interactive translation and tutoring" },
    { slug: "spirit-distillery", name: "Spirit Distillery", description: "Niche alcohol brands and clubs" },
    { slug: "subscription-socks", name: "Subscription Socks", description: "Durable recurring apparel" },
    { slug: "cbd-wellness", name: "CBD Wellness", description: "Natural health and supplements" },
    { slug: "smart-jewelry", name: "Smart Jewelry", description: "IoT accessories for women" },
    { slug: "drone-service", name: "Drone Service", description: "Aerial photography and surveying" },
    { slug: "coding-bootcamp", name: "Coding Bootcamp", description: "Online developer education" },
    { slug: "interior-design", name: "Interior Design", description: "AI-powered visualization and shopping" },
    { slug: "vending-machine", name: "Vending Machine", description: "Automated retail for niche goods" },
    { slug: "car-sharing", name: "Car Sharing", description: "P2P or fleet-based mobility" },
    { slug: "smart-mask", name: "Smart Mask", description: "Air filtration tech for urban areas" },
    { slug: "sustainable-fashion", name: "Sustainable Fashion", description: "Ethical and eco-friendly clothing" },
    { slug: "telemedicine", name: "Telemedicine", description: "Remote doctor consultations" },
    { slug: "cybersecurity", name: "Cybersecurity", description: "Small business protection and tools" },
    { slug: "hr-tech", name: "HR Tech", description: "Employee wellness and payroll" },
    { slug: "agritech", name: "Agritech", description: "Sensors and drones for farming" },
    { slug: "space-tech", name: "Space Tech", description: "Satellites and space exploration" },
    { slug: "art-marketplace", name: "Art Marketplace", description: "P2P sales for local artists" },
    { slug: "e-bike-rental", name: "E-bike Rental", description: "Micro-mobility for cities" },
    { slug: "3d-printing", name: "3D Printing", description: "On-demand manufacturing services" },
    { slug: "language-bot", name: "Language Bot", description: "AI-powered conversational learning" },
    { slug: "mental-health-bot", name: "Mental Health Bot", description: "Conversational therapy assistants" },
    { slug: "meditation-kit", name: "Meditation Kit", description: "Hardware and software for focus" },
    { slug: "sleep-tech", name: "Sleep Tech", description: "Smart mattresses and tracking" },
    { slug: "pet-grooming", name: "Pet Grooming", description: "Mobile and booking apps" },
    { slug: "sneaker-resale", name: "Sneaker Resale", description: "Authenticated trading platforms" },
    { slug: "vintage-clothing", name: "Vintage Clothing", description: "Curated thrift and resale" },
    { slug: "handmade-crafts", name: "Handmade Crafts", description: "P2P or curated shopify stores" },
    { slug: "subscription-flowers", name: "Subscription Flowers", description: "Recurring floral arrangements" },
    { slug: "smart-fridge", name: "Smart Fridge", description: "IoT inventory and grocery ordering" },
    { slug: "kitchen-robot", name: "Kitchen Robot", description: "Automation for home cooking" },
    { slug: "personal-chef", name: "Personal Chef", description: "Booking and meal planning apps" },
    { slug: "diet-app", name: "Diet App", description: "AI-driven nutrition tracking" },
    { slug: "niche-coffee", name: "Niche Coffee", description: "Ethical and high-altitude brands" },
    { slug: "brewery-club", name: "Brewery Club", description: "Subscription craft beer" },
    { slug: "wine-subscription", name: "Wine Subscription", description: "Monthly sommelier picks" },
    { slug: "whiskey-club", name: "Whiskey Club", description: "Niche spirit monthly boxes" },
    { slug: "subscription-box", name: "Subscription Box", description: "General curation services" },
    { slug: "smart-irrigation", name: "Smart Irrigation", description: "IoT for garden and lawn care" },
    { slug: "community-app", name: "Community App", description: "Niche networks for hobbyists" },
    { slug: "influencer-tools", name: "Influencer Tools", description: "Media kits and sponsorship tracking" },
    { slug: "streaming-tool", name: "Streaming Tool", description: "Overlays and alert software" },
    { slug: "indie-game-mod", name: "Indie Game Mod", description: "Tools for enhancing existing games" },
    { slug: "fan-fiction", name: "Fan Fiction", description: "Platforms for community storytelling" },
    { slug: "digital-art", name: "Digital Art", description: "Brush sets and asset packs" },
    { slug: "vr-training", name: "VR Training", description: "Workplace safety and skill sim" },
    { slug: "ar-furniture", name: "AR Furniture", description: "Visualize decor in home" },
    { slug: "smart-watch-face", name: "Smart Watch Face", description: "Design and sales for wearables" },
    { slug: "habit-tracker", name: "Habit Tracker", description: "Gamified routine apps" },
    { slug: "focus-music", name: "Focus Music", description: "AI-generated binaural beats" },
    { slug: "smart-pillow", name: "Smart Pillow", description: "Cooling and tracking for sleep" },
    { slug: "ai-writing", name: "AI Writing", description: "Niche copy and content aid" },
    { slug: "legal-doc-bot", name: "Legal Doc Bot", description: "Automated contract generation" },
    { slug: "tax-automation", name: "Tax Automation", description: "Simplified filing for freelancers" }
];
