import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import { generateValidationReport } from './src/lib/generator.js';

dotenv.config();

const supabase = createClient(
    process.env.VITE_SUPABASE_URL,
    process.env.VITE_SUPABASE_ANON_KEY
);

export async function generateAuthorityPosts() {
    console.log("✍️ Starting Authority Content Generation...");

    // 1. Fetch high-score leads that don't have a narrative yet
    const { data: leads, error } = await supabase
        .from('leads')
        .select('*')
        .not('results', 'is', null)
        .is('expert_narrative', null)
        .order('created_at', { ascending: false })
        .limit(10);

    if (error) {
        console.error("❌ Error fetching leads:", error);
        return;
    }

    if (!leads || leads.length === 0) {
        console.log("✅ No new high-score validations found for processing.");
        return;
    }

    for (const lead of leads) {
        try {
            const results = lead.results;
            const niche = results.niche || "this niche";
            const name = lead.project_name || "this project";
            const revenue = results.revenueForecast?.estimatedAnnualRevenue || "significant";

            // 2. Build the "Expert Narrative" (Programmatic Blog Post)
            const narrative = `
## Deep Dive: Why ${name} has Six-Figure Potential in the ${niche} Space

After analyzing thousands of data points across Reddit and X, it's clear that ${name} isn't just another startup idea—it's a targeted solution for a high-intent pain point. Here is our expert breakdown of why this validation scored an impressive ${results.overallScore}/10.

### 🎯 Market Alignment & Intent
The core strength of ${name} lies in its perfect alignment with the ${results.targetAudience?.primarySegment || 'target audience'}. We detected significant "buying intent" signals for keywords related to "${niche}." Unlike generic solutions, ${name} addresses the specific friction of ${results.targetAudience?.painPoints?.[0] || 'manual overhead'}.

### 💰 The Revenue Engine
With an estimated annual revenue potential of **$${revenue}**, this niche is ripe for a specialized player. Our TAM/SAM/SOM model shows a realistic capture rate of 1.5% in the first 12 months, driven by the low barrier to entry for ${results.targetAudience?.primarySegment}. 

### 🛡️ Competitive Moat
While players like ${results.competitorIntelligence?.[0]?.name || 'existing incumbents'} dominate the broad market, they suffer from ${results.competitorIntelligence?.[0]?.weakness || 'complexity'}. ${name} wins by focusing on **simplicity** and **niche-specific automation**.

#### 🔗 Discovery Roadmap
To win in this space, we recommend the 30-day playbook generated in the full report. If you're building in the [${niche}](/validate/${niche.toLowerCase().replace(/ /g, '-')}) space, you need to prioritize visibility in Week 1.

**Free Tools for this Niche:**
- 🚀 **Niche Naming**: [Generate viral names for ${niche}](/tools/naming)
- 📊 **TAM Estimator**: [Calculate ${niche} market size](/tools/market-size)
- 📰 **Live Trends**: [Scan ${niche} momentum data](/newsroom)

*This analysis was programmatically generated by the MarketVibe Authority Engine (AEO-v4) based on live market intent data.*
            `.trim();

            // 3. Persist the Narrative directly into the results JSONB
            const updatedResults = {
                ...results,
                expertNarrative: narrative
            };

            const { error: updateError } = await supabase
                .from('leads')
                .update({
                    results: updatedResults,
                    expert_narrative: narrative // Keeping separate column for indexing/search if needed
                })
                .eq('id', lead.id);

            if (updateError) throw updateError;
            console.log(`✅ Generated Deep Dive for: ${name}`);

        } catch (err) {
            console.error(`❌ Error processing lead ${lead.id}:`, err.message);
        }
    }

    console.log("🏁 Authority Content Cycle Complete.");
}

// Auto-run if executed directly
const isDirectRun = import.meta.url.includes(process.argv[1]?.replace(/\\/g, '/')) ||
    import.meta.url.endsWith(process.argv[1]?.split(/[\\/]/).pop());

if (isDirectRun) {
    generateAuthorityPosts();
}
