import React, { useState, useEffect } from 'react';
import trendsData from '../lib/trends_cache.json';
import { popularNiches } from '../lib/niches';

const Newsroom = () => {
    const [trends, setTrends] = useState([]);

    useEffect(() => {
        // In a real app, this might fetch from an API endpoint
        // For now, we load the static cache generated by the agent
        setTrends(trendsData);
    }, []);

    const getSlug = (nicheName) => {
        // Try to find exact match in popularNiches
        const found = popularNiches.find(n => n.name.toLowerCase() === nicheName.toLowerCase());
        if (found) return found.slug;

        // Fallback slugify
        return nicheName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    };

    return (
        <div className="container" style={{ padding: '4rem 0' }}>
            <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
                <span style={{
                    background: '#ef4444',
                    color: 'white',
                    padding: '0.25rem 0.75rem',
                    borderRadius: '0.25rem',
                    fontSize: '0.8rem',
                    fontWeight: 'bold',
                    letterSpacing: '1px',
                    marginBottom: '1rem',
                    display: 'inline-block'
                }}>
                    LIVE MARKET INTELLIGENCE
                </span>
                <h1 style={{ fontSize: '3.5rem', fontWeight: '900', margin: '0 0 1rem 0' }}>The Newsroom 📰</h1>
                <p style={{ color: '#94a3b8', fontSize: '1.2rem', maxWidth: '600px', margin: '0 auto' }}>
                    Real-time breakout trends detected by our autonomous agents.
                </p>
            </div>

            <div style={{ display: 'grid', gap: '2rem', maxWidth: '800px', margin: '0 auto' }}>
                {trends.map((trend, index) => (
                    <div key={index} style={{
                        background: 'rgba(255,255,255,0.03)',
                        borderRadius: '1rem',
                        border: '1px solid rgba(255,255,255,0.05)',
                        padding: '2rem',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '2rem',
                        position: 'relative',
                        overflow: 'hidden'
                    }}>
                        <div style={{
                            fontSize: '4rem',
                            fontWeight: '900',
                            color: 'rgba(255,255,255,0.05)',
                            lineHeight: 1,
                            minWidth: '60px',
                            textAlign: 'center'
                        }}>
                            {index + 1}
                        </div>

                        <div style={{ flex: 1 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '0.5rem' }}>
                                <h2 style={{ margin: 0, fontSize: '1.5rem', fontWeight: 'bold' }}>{trend.niche}</h2>
                                <span style={{
                                    color: '#ef4444',
                                    background: 'rgba(239, 68, 68, 0.1)',
                                    padding: '0.2rem 0.6rem',
                                    borderRadius: '1rem',
                                    fontSize: '0.75rem',
                                    fontWeight: 'bold',
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: '0.25rem'
                                }}>
                                    🔥 {trend.velocity} New Signals
                                </span>
                            </div>
                            <p style={{ color: '#94a3b8', margin: 0, fontSize: '0.9rem' }}>
                                High momentum detected. Founders are actively validating this space right now.
                            </p>
                        </div>

                        <a
                            href={`/validate/${getSlug(trend.niche)}`}
                            style={{
                                background: '#6366f1',
                                color: 'white',
                                textDecoration: 'none',
                                padding: '1rem 2rem',
                                borderRadius: '0.75rem',
                                fontWeight: 'bold',
                                whiteSpace: 'nowrap',
                                transition: 'transform 0.2s',
                                boxShadow: '0 4px 14px 0 rgba(99, 102, 241, 0.39)'
                            }}
                            onMouseOver={(e) => e.currentTarget.style.transform = 'scale(1.05)'}
                            onMouseOut={(e) => e.currentTarget.style.transform = 'scale(1)'}
                        >
                            Launch This 🚀
                        </a>
                    </div>
                ))}
            </div>

            <div style={{ textAlign: 'center', marginTop: '4rem', color: '#64748b', fontSize: '0.9rem' }}>
                <p>Data updated every 4 hours based on global validation activity.</p>
            </div>
        </div>
    );
};

export default Newsroom;
