import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { niches } from '../lib/niches';
import { generateValidationReport } from '../lib/generator';

const NicheValidator = () => {
    const { nicheId } = useParams();
    const [nicheData, setNicheData] = useState(null);
    const [report, setReport] = useState(null);

    useEffect(() => {
        const found = niches.find(n => n.id === nicheId) || niches[0];
        setNicheData(found);

        // Generate a sample preview report for the niche
        const sampleReport = generateValidationReport({
            name: found.name,
            description: `How to build and validate a ${found.name} business in 30 days.`,
            audience: found.audience || "Founders & Builders",
            niche: found.name
        });
        setReport(sampleReport);

        // Update document title for SEO
        document.title = `Validate ${found.name} Startup Idea - MarketVibe`;
    }, [nicheId]);

    if (!nicheData || !report) return null;

    return (
        <div style={{ padding: '4rem 2rem', maxWidth: '1200px', margin: '0 auto', color: 'white' }}>
            <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
                <span style={{ color: '#6366f1', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                    Programmatic Validation Guide
                </span>
                <h1 style={{ fontSize: '3.5rem', marginTop: '1rem', fontWeight: '900' }}>
                    How to Validate a <span style={{ color: '#6366f1' }}>{nicheData.name}</span> Startup
                </h1>
                <p style={{ fontSize: '1.2rem', color: '#94a3b8', maxWidth: '800px', margin: '1.5rem auto' }}>
                    Stop guessing. Here is the data-backed blueprint for the {nicheData.name} niche, generated by MarketVibe AI.
                </p>
                <Link to="/" style={{
                    display: 'inline-block',
                    background: '#6366f1',
                    color: 'white',
                    padding: '1rem 2rem',
                    borderRadius: '0.5rem',
                    textDecoration: 'none',
                    fontWeight: 'bold',
                    marginTop: '1rem'
                }}>
                    Validate Your Custom Idea Now
                </Link>
            </div>

            <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
                gap: '2rem',
                background: 'rgba(255,255,255,0.02)',
                padding: '3rem',
                borderRadius: '1.5rem',
                border: '1px solid rgba(255,255,255,0.1)'
            }}>
                <div>
                    <h3 style={{ color: '#6366f1' }}>📊 Market Outlook</h3>
                    <p style={{ color: '#94a3b8' }}>
                        The {nicheData.name} market is currently estimated at a <strong>${report.revenueForecast.marketSize}</strong> opportunity.
                        With a validation score of <strong>{report.overallScore}/10</strong>, now is the prime time to build.
                    </p>
                </div>
                <div>
                    <h3 style={{ color: '#10b981' }}>🎯 Target Audience</h3>
                    <p style={{ color: '#94a3b8' }}>
                        Your primary segment is <strong>{report.targetAudience.primarySegment}</strong>.
                        We recommend starting with a focus on {report.targetAudience.earlyAdopters}.
                    </p>
                </div>
                <div>
                    <h3 style={{ color: '#f59e0b' }}>💰 Revenue Forecast</h3>
                    <p style={{ color: '#94a3b8' }}>
                        Est. First Year Revenue: <strong>${report.revenueForecast.estimatedAnnualRevenue}</strong>.
                        Recommended pricing model: <strong>{report.monetization.pricingModel}</strong>.
                    </p>
                </div>
            </div>

            <div style={{ marginTop: '4rem', padding: '2rem', background: 'rgba(99, 102, 241, 0.1)', borderRadius: '1rem', border: '1px solid rgba(99, 102, 241, 0.2)' }}>
                <h2>🚀 30-Day Execution Blueprint</h2>
                {report.executionBlueprint.phases.map((phase, idx) => (
                    <div key={idx} style={{ marginBottom: '1.5rem' }}>
                        <h4 style={{ color: '#6366f1', marginBottom: '0.5rem' }}>Phase {idx + 1}: {phase.title}</h4>
                        <p style={{ color: '#94a3b8', margin: 0 }}>{phase.focus}</p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default NicheValidator;
