import React, { useEffect, useState } from 'react';
import { popularNiches } from '../lib/niches';
import { generateValidationReport } from '../lib/generator';

const NicheValidator = () => {
    const [nicheData, setNicheData] = useState(null);
    const [report, setReport] = useState(null);

    useEffect(() => {
        // 1. Determine Niche (Slug from URL or Default)
        const pathParts = window.location.pathname.split('/');
        const slugFromUrl = pathParts[pathParts.length - 1];

        // Use URL slug, or default to 'saas' if landing on /validate or empty
        const found = popularNiches.find(n => n.slug === slugFromUrl) || popularNiches.find(n => n.slug === 'saas');

        setNicheData(found);

        // 2. Generate Report Data
        try {
            const sampleReport = generateValidationReport({
                name: found.name,
                description: `How to build and validate a ${found.name} business in 30 days.`,
                audience: found.audience || "Founders & Builders",
                niche: found.name
            });
            setReport(sampleReport);
        } catch (err) {
            console.error("[NicheValidator] Failed to generate report:", err);
        }

        document.title = `Validate ${found.name} Startup Idea - MarketVibe`;
    }, []);

    if (!nicheData || !report) {
        return (
            <div style={{ padding: '10rem', textAlign: 'center', color: 'white' }}>
                <h2 style={{ color: '#6366f1' }}>📚 Initializing Validation Library...</h2>
                <p style={{ color: '#94a3b8', marginTop: '1rem' }}>Preparing market data and revenue models.</p>
                <a href="/" style={{ color: '#6366f1', textDecoration: 'none', marginTop: '2rem', display: 'inline-block' }}>➜ Back to Dashboard</a>
            </div>
        );
    }

    return (
        <div style={{ padding: '4rem 2rem', maxWidth: '1200px', margin: '0 auto', color: 'white' }}>
            <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
                <span style={{ color: '#6366f1', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
                    Programmatic Validation Guide
                </span>
                <h1 style={{ fontSize: '3.5rem', marginTop: '1rem', fontWeight: '900' }}>
                    How to Validate a <span style={{ color: '#6366f1' }}>{nicheData.name}</span> Startup
                </h1>
                <p style={{ fontSize: '1.2rem', color: '#94a3b8', maxWidth: '800px', margin: '1.5rem auto' }}>
                    Stop guessing. Here is the data-backed blueprint for the {nicheData.name} niche, generated by MarketVibe AI.
                </p>
                <a href="/" style={{
                    display: 'inline-block',
                    background: '#6366f1',
                    color: 'white',
                    padding: '1rem 2rem',
                    borderRadius: '0.5rem',
                    textDecoration: 'none',
                    fontWeight: 'bold',
                    marginTop: '1rem'
                }}>
                    Validate Your Custom Idea Now
                </a>
            </div>

            <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
                gap: '2rem',
                background: 'rgba(255,255,255,0.02)',
                padding: '3rem',
                borderRadius: '1.5rem',
                border: '1px solid rgba(255,255,255,0.1)'
            }}>
                <div>
                    <h3 style={{ color: '#6366f1' }}>📊 Market Outlook</h3>
                    <p style={{ color: '#94a3b8' }}>
                        The {nicheData.name} market is currently estimated at a <strong>${report.revenueForecast.marketSize}</strong> opportunity.
                        This niche shows strong entry potential for bootstrapped founders.
                    </p>
                </div>
                <div>
                    <h3 style={{ color: '#10b981' }}>🎯 Target Audience</h3>
                    <p style={{ color: '#94a3b8' }}>
                        Your primary segment is <strong>{report.targetAudience.primarySegment}</strong>.
                        Focus on the pain point: <em>{report.targetAudience.painPoints?.[0] || 'Market Efficiency'}</em>.
                    </p>
                </div>
                <div>
                    <h3 style={{ color: '#f59e0b' }}>💰 Revenue Forecast</h3>
                    <p style={{ color: '#94a3b8' }}>
                        Est. First Year Revenue: <strong>${report.revenueForecast.estimatedAnnualRevenue}</strong>.
                        Recommended pricing: <strong>{report.revenueForecast.pricingTiers?.[0]?.price || '$49'}/mo</strong>.
                    </p>
                </div>
            </div>

            <div style={{ marginTop: '4rem', padding: '2rem', background: 'rgba(99, 102, 241, 0.1)', borderRadius: '1rem', border: '1px solid rgba(99, 102, 241, 0.2)' }}>
                <h2 style={{ marginBottom: '2rem' }}>🚀 30-Day Execution Blueprint</h2>
                <div style={{ display: 'grid', gap: '2rem' }}>
                    {report.executionPlan?.map((week, idx) => (
                        <div key={idx} style={{ background: 'rgba(255,255,255,0.02)', padding: '2rem', borderRadius: '1rem' }}>
                            <h3 style={{ color: '#6366f1', marginBottom: '1.5rem' }}>{week.week}</h3>
                            <div style={{ display: 'grid', gap: '1rem' }}>
                                {week.tasks.map((t, tIdx) => (
                                    <div key={tIdx} style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
                                        <div style={{ color: '#6366f1', fontSize: '0.8rem', fontWeight: 'bold', background: 'rgba(99, 102, 241, 0.1)', padding: '0.2rem 0.6rem', borderRadius: '0.4rem' }}>{t.day}</div>
                                        <div style={{ color: '#cbd5e1' }}>{t.task}</div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default NicheValidator;
